/*
 * TMS320C6452 Core Access Layer - Implementation
 * Auto-generated by ag-drv-CodeGen Agent
 */

#include "titusbspgit/DeviceDrivers/GPIO/TMS320C6452/TMS320C6452_core.h"

/* Define function pointers table */
const tms320c6452_core_ops_t TMS320C6452_core_ops = {
    .read8     = tms320c6452_read8,
    .write8    = tms320c6452_write8,
    .read16    = tms320c6452_read16,
    .write16   = tms320c6452_write16,
    .read32    = tms320c6452_read32,
    .write32   = tms320c6452_write32,
    .read64    = tms320c6452_read64,
    .write64   = tms320c6452_write64,
    .set_bits32= tms320c6452_set_bits32,
    .clr_bits32= tms320c6452_clr_bits32,
    .dmb       = tms320c6452_dmb,
    .dsb       = tms320c6452_dsb,
    .isb       = tms320c6452_isb,
};
