/*
 * TMS320C6452 Core Access Layer (U-Boot style)
 * Auto-generated by ag-drv-CodeGen Agent
 */

#ifndef TMS320C6452_CORE_H
#define TMS320C6452_CORE_H

/* Environment assumptions:
 * - Freestanding C99, gcc
 * - Target: arm (cross-building helper layer for big-endian MMIO targets)
 * - Endianness: big-endian device registers
 */

#include <stdint.h>
#include <stddef.h>

/* Base address root for SoC configuration/peripherals as seen by CPU */
#ifndef TMS320C6452_BASE
#define TMS320C6452_BASE ((uintptr_t)0x18000000u)
#endif

/* Generic accessor to compute a register address from base + offset */
#define TMS320C6452_REG_ADDR(off) ((volatile void *)((uintptr_t)TMS320C6452_BASE + (uintptr_t)(off)))

/* Placeholder pattern macros for feature drivers to compose block bases.
 * Example usage in a feature header:
 *   #define TMS320C6452_<BLOCK>_BASE   (TMS320C6452_BASE + 0xOFFSET)
 *   #define TMS320C6452_<BLOCK>_REG(x) ((uintptr_t)(TMS320C6452_<BLOCK>_BASE) + (x))
 */

/* Memory barriers and CPU sync primitives (portable subset for U-Boot-like env) */
#if defined(__arm__) || defined(__aarch64__)
static inline void tms320c6452_dmb(void) {
#if defined(__aarch64__)
    __asm__ __volatile__("dmb ish" ::: "memory");
#else
    __asm__ __volatile__("dmb" ::: "memory");
#endif
}
static inline void tms320c6452_dsb(void) {
#if defined(__aarch64__)
    __asm__ __volatile__("dsb ish" ::: "memory");
#else
    __asm__ __volatile__("dsb" ::: "memory");
#endif
}
static inline void tms320c6452_isb(void) {
#if defined(__aarch64__)
    __asm__ __volatile__("isb" ::: "memory");
#else
    __asm__ __volatile__("isb" ::: "memory");
#endif
}
#else
/* Fallback no-ops on other arch when building tools/tests */
static inline void tms320c6452_dmb(void) { __asm__ __volatile__("" ::: "memory"); }
static inline void tms320c6452_dsb(void) { __asm__ __volatile__("" ::: "memory"); }
static inline void tms320c6452_isb(void) { __asm__ __volatile__("" ::: "memory"); }
#endif

/* Big-endian MMIO helpers: all register accesses go through these.
 * We intentionally do not use host byte-order dependent builtins; instead,
 * we implement explicit byte swapping when the compiler/host is little-endian.
 */

/* Compile-time detection of host endianness for accessors */
#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#define HOST_IS_BIG_ENDIAN 1
#else
#define HOST_IS_BIG_ENDIAN 0
#endif

static inline uint16_t be16_to_cpu(uint16_t x) {
#if HOST_IS_BIG_ENDIAN
    return x;
#else
    return (uint16_t)((x >> 8) | (x << 8));
#endif
}

static inline uint32_t be32_to_cpu(uint32_t x) {
#if HOST_IS_BIG_ENDIAN
    return x;
#else
    return ((x & 0x000000FFu) << 24) |
           ((x & 0x0000FF00u) << 8)  |
           ((x & 0x00FF0000u) >> 8)  |
           ((x & 0xFF000000u) >> 24);
#endif
}

static inline uint64_t be64_to_cpu(uint64_t x) {
#if HOST_IS_BIG_ENDIAN
    return x;
#else
    return ((x & 0x00000000000000FFull) << 56) |
           ((x & 0x000000000000FF00ull) << 40) |
           ((x & 0x0000000000FF0000ull) << 24) |
           ((x & 0x00000000FF000000ull) << 8)  |
           ((x & 0x000000FF00000000ull) >> 8)  |
           ((x & 0x0000FF0000000000ull) >> 24) |
           ((x & 0x00FF000000000000ull) >> 40) |
           ((x & 0xFF00000000000000ull) >> 56);
#endif
}

static inline uint16_t cpu_to_be16(uint16_t x) { return be16_to_cpu(x); }
static inline uint32_t cpu_to_be32(uint32_t x) { return be32_to_cpu(x); }
static inline uint64_t cpu_to_be64(uint64_t x) { return be64_to_cpu(x); }

/* Volatile MMIO read/write primitives */
static inline uint8_t  tms320c6452_read8(uintptr_t addr)  { return *(volatile uint8_t *)addr; }
static inline void     tms320c6452_write8(uintptr_t addr, uint8_t v) { *(volatile uint8_t *)addr = v; }

static inline uint16_t tms320c6452_read16(uintptr_t addr) {
    uint16_t v = *(volatile uint16_t *)addr;
    return be16_to_cpu(v);
}
static inline void     tms320c6452_write16(uintptr_t addr, uint16_t v) {
    *(volatile uint16_t *)addr = cpu_to_be16(v);
}

static inline uint32_t tms320c6452_read32(uintptr_t addr) {
    uint32_t v = *(volatile uint32_t *)addr;
    return be32_to_cpu(v);
}
static inline void     tms320c6452_write32(uintptr_t addr, uint32_t v) {
    *(volatile uint32_t *)addr = cpu_to_be32(v);
}

static inline uint64_t tms320c6452_read64(uintptr_t addr) {
    uint64_t v = *(volatile uint64_t *)addr;
    return be64_to_cpu(v);
}
static inline void     tms320c6452_write64(uintptr_t addr, uint64_t v) {
    *(volatile uint64_t *)addr = cpu_to_be64(v);
}

/* Bit helpers for read-modify-write with barriers */
static inline void tms320c6452_set_bits32(uintptr_t addr, uint32_t mask) {
    uint32_t v = tms320c6452_read32(addr);
    v |= mask;
    tms320c6452_write32(addr, v);
    tms320c6452_dmb();
}

static inline void tms320c6452_clr_bits32(uintptr_t addr, uint32_t mask) {
    uint32_t v = tms320c6452_read32(addr);
    v &= ~mask;
    tms320c6452_write32(addr, v);
    tms320c6452_dmb();
}

/* Core ops table to expose helpers to feature drivers */
typedef struct tms320c6452_core_ops_s {
    uint8_t  (*read8)(uintptr_t addr);
    void     (*write8)(uintptr_t addr, uint8_t v);
    uint16_t (*read16)(uintptr_t addr);
    void     (*write16)(uintptr_t addr, uint16_t v);
    uint32_t (*read32)(uintptr_t addr);
    void     (*write32)(uintptr_t addr, uint32_t v);
    uint64_t (*read64)(uintptr_t addr);
    void     (*write64)(uintptr_t addr, uint64_t v);
    void     (*set_bits32)(uintptr_t addr, uint32_t mask);
    void     (*clr_bits32)(uintptr_t addr, uint32_t mask);
    void     (*dmb)(void);
    void     (*dsb)(void);
    void     (*isb)(void);
} tms320c6452_core_ops_t;

extern const tms320c6452_core_ops_t TMS320C6452_core_ops;

#endif /* TMS320C6452_CORE_H */
