/*
 * Copyright (c) 2026
 * SPDX-License-Identifier: MIT
 * Common HAL and utilities for Synopsys DesignWare PCIe (DM v6.00a) - ARM big-endian
 * Generated by RCI-ag-DrvGen Agent
 */
#ifndef PCIE_HAL_H
#define PCIE_HAL_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Build-time flag to disable byte-swap for host/mock tests */
#ifndef PCIE_HAL_HOST_TEST
#define PCIE_HAL_HOST_TEST (0)
#endif

/* Compile-time endianness checks (build intended for big-endian) */
#if defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__)
# if (__BYTE_ORDER__ != __ORDER_BIG_ENDIAN__)
#  if (PCIE_HAL_HOST_TEST)
#   pragma message ("PCIE_HAL_HOST_TEST enabled: disabling MMIO byte-swap for host tests")
#  else
#   warning "Building for non-big-endian target; MMIO helpers will byte-swap if needed."
#  endif
# endif
#endif

typedef enum
{
    PCIE_STATUS_OK = 0,
    PCIE_STATUS_ERROR = -1,
    PCIE_STATUS_TIMEOUT = -2,
    PCIE_STATUS_UNSUPPORTED = -3,
    PCIE_STATUS_BUSY = -4,
    PCIE_STATUS_INVALID_ARG = -5
} pcie_status_t;

/* DBI context: reentrant if distinct contexts are used. */
typedef struct
{
    volatile uint8_t* dbi;   /* Base of DBI/config space */
    size_t            dbi_size;
} pcie_dbi_t;

/* Weak hook for delay; platform may override. Units: microseconds */
void pcie_hal_udelay(uint32_t usec);

/* Memory barriers */
static inline void pcie_wmb(void) { __asm__ volatile ("" ::: "memory"); }
static inline void pcie_rmb(void) { __asm__ volatile ("" ::: "memory"); }

/* Big-endian MMIO accessors (32/64-bit) */
static inline uint32_t pcie_read32(const pcie_dbi_t* ctx, uint32_t off)
{
    volatile uint32_t* p = (volatile uint32_t*)(ctx->dbi + off);
#if (PCIE_HAL_HOST_TEST)
    return *p; /* host tests: do not swap */
#else
# if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
    uint32_t v = *p;
    v = __builtin_bswap32(v);
    return v;
# else
    return *p;
# endif
#endif
}

static inline void pcie_write32(pcie_dbi_t* ctx, uint32_t off, uint32_t val)
{
    volatile uint32_t* p = (volatile uint32_t*)(ctx->dbi + off);
#if (PCIE_HAL_HOST_TEST)
    *p = val;
#else
# if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
    *p = __builtin_bswap32(val);
# else
    *p = val;
# endif
#endif
    pcie_wmb();
}

static inline void pcie_rmw32(pcie_dbi_t* ctx, uint32_t off, uint32_t clr_mask, uint32_t set_mask)
{
    uint32_t v = pcie_read32(ctx, off);
    v = (v & (~clr_mask)) | set_mask;
    pcie_write32(ctx, off, v);
}

/* Initialize DBI context */
static inline pcie_status_t pcie_init(pcie_dbi_t* ctx, volatile void* dbi_base, size_t dbi_size)
{
    if ((ctx == NULL) || (dbi_base == NULL) || (dbi_size < 0x100u)) {
        return PCIE_STATUS_INVALID_ARG;
    }
    ctx->dbi = (volatile uint8_t*)dbi_base;
    ctx->dbi_size = dbi_size;
    return PCIE_STATUS_OK;
}

/* PCI configuration space basics */
#define PCI_CFG_CAP_PTR_OFF                 (0x34u) /* 8-bit Ptr to first PCI capability */
#define PCI_CAP_ID_PCI_EXP                  (0x10u) /* Standard PCI Express Capability ID */

/* Access helpers */
static inline uint8_t pcie_read8(const pcie_dbi_t* ctx, uint32_t off)
{
    volatile uint8_t* p = (volatile uint8_t*)(ctx->dbi + off);
    return *p;
}

static inline void pcie_write8(pcie_dbi_t* ctx, uint32_t off, uint8_t v)
{
    volatile uint8_t* p = (volatile uint8_t*)(ctx->dbi + off);
    *p = v;
    pcie_wmb();
}

static inline uint16_t pcie_read16(const pcie_dbi_t* ctx, uint32_t off)
{
    volatile uint16_t* p = (volatile uint16_t*)(ctx->dbi + off);
#if (PCIE_HAL_HOST_TEST)
    return *p;
#else
# if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
    uint16_t v = *p;
    v = __builtin_bswap16(v);
    return v;
# else
    return *p;
# endif
#endif
}

static inline void pcie_write16(pcie_dbi_t* ctx, uint32_t off, uint16_t v)
{
    volatile uint16_t* p = (volatile uint16_t*)(ctx->dbi + off);
#if (PCIE_HAL_HOST_TEST)
    *p = v;
#else
# if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
    *p = __builtin_bswap16(v);
# else
    *p = v;
# endif
#endif
    pcie_wmb();
}

/* Capability discovery (Standard PCI capability list starting at offset 0x34) */
static inline uint32_t pcie_find_pci_cap(const pcie_dbi_t* ctx, uint8_t cap_id)
{
    uint8_t ptr = pcie_read8(ctx, PCI_CFG_CAP_PTR_OFF) & (uint8_t)~0x3u;
    uint32_t limit = 0u;
    while ((ptr != 0u) && (limit < 48u)) {
        uint8_t id = pcie_read8(ctx, (uint32_t)ptr);
        if (id == cap_id) {
            return (uint32_t)ptr;
        }
        ptr = pcie_read8(ctx, (uint32_t)ptr + 1u) & (uint8_t)~0x3u; /* Next pointer in byte[1] */
        limit++;
    }
    return 0u;
}

/* Extended capability discovery (starts at 0x100, 4-byte aligned) */
static inline uint32_t pcie_find_ext_cap(const pcie_dbi_t* ctx, uint16_t ext_cap_id)
{
    uint32_t off = 0x100u;
    uint32_t limit = 0u;
    while ((off != 0u) && (off < ctx->dbi_size) && (limit < 1024u)) {
        uint32_t hdr = pcie_read32(ctx, off);
        if ((hdr & 0xFFFFu) == (uint32_t)ext_cap_id) {
            return off;
        }
        uint32_t next = (hdr >> 20) & 0xFFFu;
        if (next == 0u) { break; }
        off = next;
        limit++;
    }
    return 0u;
}

/* Selected PCIe Capability fields/offsets (assumptions documented in MISRA_DEVIATIONS.md) */
#define PCIE_CAP_REG_PXCAP           (0x02u) /* PCIe Capabilities Register (16-bit) */
#define PCIE_CAP_REG_DEV_CAP2        (0x24u) /* Device Capabilities 2 (32-bit) */
#define PCIE_CAP_REG_DEV_CTRL2_STAT2 (0x28u) /* Device Control 2 / Status 2 (32-bit) */
#define PCIE_CAP_REG_LINK_CAP2       (0x2Cu) /* Link Capabilities 2 (32-bit) */
#define PCIE_CAP_REG_LINK_CTRL2_STAT2 (0x30u)/* Link Control 2 / Status 2 (32-bit) */
#define PCIE_CAP_REG_DEV_CAP3        (0x38u) /* Device Capabilities 3 (32-bit) */
#define PCIE_CAP_REG_LINK_CTRL3_STAT3 (0x3Cu)/* Link Control 3 [15:0] / Status 3 [31:16] */

/* RAG-confirmed/assumed field bits */
#define DEV_CAP3_FLIT_MODE_SUPP      (1u << 0)   /* RAG: Device Cap 3 indicates FLIT support */
#define LINK_CTRL3_FLIT_MODE_ENABLE  (1u << 13)  /* Assumption; varies by config, see config header */
#define LINK_STATUS2_FLIT_MODE_ACTIVE (1u << 26) /* Assumption; varies by config, see config header */

/* Extended Capability IDs */
#define PCIE_EXTCAP_ID_L1SUB         (0x001Eu)
#define PCIE_EXTCAP_ID_SPCIE         (0x0019u)
#define PCIE_EXTCAP_ID_PL64G         (0x0031u)

/* DWC Port Logic (DBI) vendor offsets (absolute offsets within DBI window) */
#define DWC_PORT_VSDLLP_OFF          (0x704u) /* VENDOR_SPEC_DLLP */
#define DWC_PORT_FORCE_OFF           (0x708u) /* PORT_FORCE */
#define DWC_GEN3_RELATED_OFF         (0x890u) /* GEN3_RELATED */
#define DWC_GEN3_EQ_LOCAL_FS_LF_OFF  (0x894u) /* GEN3_EQ_LOCAL_FS_LF */
#define DWC_GEN3_EQ_PSET_COEF_MAP_OFF (0x898u)/* Presets->Coeff map */
#define DWC_GEN3_EQ_PRESET_INDEX_OFF  (0x89Cu)/* Preset index */
#define DWC_GEN3_EQ_STATUS_OFF        (0x8A4u)/* EQ status */

/* PHY viewport registers */
#define DWC_PHY_VIEWPORT_CTLSTS_OFF  (0xB70u)
#define DWC_PHY_VIEWPORT_DATA_OFF    (0xB74u)

#ifdef __cplusplus
}
#endif

#endif /* PCIE_HAL_H */
