/*
 * MIT License
 * Common HAL impl for Synopsys DWC PCIe (DM v6.00a) - ARM big-endian
 * Generated by RCI-ag-DrvGen Agent
 */
#include "pcie_hal.h"

/* Default weak udelay: simple empty loop (not precise). Platform should override. */
__attribute__((weak)) void pcie_hal_udelay(uint32_t usec)
{
    volatile uint32_t n = usec * 16u; /* crude */
    while (n > 0u) { n--; }
}
