#ifndef CORE_KEYSTONE_PCIE_MODULE_H
#define CORE_KEYSTONE_PCIE_MODULE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* Global configuration (autogenerated) */
#define KPM_ARCH_ARM            1
#define KPM_ENV_BAREMETAL       1
#define KPM_COMPILER_GCC        1
#define KPM_BIG_ENDIAN          1

/* Base address of the controller */
#define KPM_BASE_ADDR           ((uintptr_t)0xA1008000u)

/* Memory barriers for ARM (GCC) */
#if defined(__arm__) || defined(__aarch64__)
#define KPM_DMB() __asm__ volatile("dmb sy" ::: "memory")
#define KPM_DSB() __asm__ volatile("dsb sy" ::: "memory")
#define KPM_ISB() __asm__ volatile("isb" ::: "memory")
#else
#define KPM_DMB() do {} while(0)
#define KPM_DSB() do {} while(0)
#define KPM_ISB() do {} while(0)
#endif

/* Deterministic MMIO access helpers */
static inline uint32_t kpm_mmio_read32(uintptr_t base, uintptr_t off)
{
    volatile const uint32_t *addr = (volatile const uint32_t *)(base + off);
    KPM_DMB();
    uint32_t v = *addr;   /* Big-endian CPU assumed; no byte swap here */
    KPM_DMB();
    return v;
}

static inline void kpm_mmio_write32(uintptr_t base, uintptr_t off, uint32_t v)
{
    volatile uint32_t *addr = (volatile uint32_t *)(base + off);
    KPM_DMB();
    *addr = v;            /* Big-endian CPU assumed; no byte swap here */
    KPM_DMB();
}

/* Core API structure exposed to feature drivers */
typedef struct KPM_CoreApi {
    uintptr_t base;
    uint32_t  (*read32)(uintptr_t base, uintptr_t off);
    void      (*write32)(uintptr_t base, uintptr_t off, uint32_t v);
} KPM_CoreApi;

/* Obtain a copy of the core API (by value) */
static inline KPM_CoreApi kpm_core_get_api(void)
{
    KPM_CoreApi api;
    api.base   = KPM_BASE_ADDR;
    api.read32 = &kpm_mmio_read32;
    api.write32= &kpm_mmio_write32;
    return api;
}

#endif /* CORE_KEYSTONE_PCIE_MODULE_H */
