/*
 * TMS320C6452 DSP Core MMIO Access - Reusable Core Layer (Implementation)
 * Environment: ARM GCC Baremetal, Big-Endian register view
 * Generated by RCI-ag-DrvGen Agent
 */
#include "TMS320C6452 DSP_core.h"

/* -------------------------------------------------------------------------- */
/* Endianness helpers                                                          */
/* -------------------------------------------------------------------------- */
#if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
#define RCI_CPU_LITTLE_ENDIAN 1
#elif defined(__ARMEL__)
#define RCI_CPU_LITTLE_ENDIAN 1
#else
#define RCI_CPU_LITTLE_ENDIAN 0
#endif

static inline uint16_t rci_bswap16(uint16_t v)
{
    return (uint16_t)(((uint16_t)(v >> 8)) | (uint16_t)(v << 8));
}

static inline uint32_t rci_bswap32(uint32_t v)
{
    return ((v & 0x000000FFu) << 24)
         | ((v & 0x0000FF00u) << 8)
         | ((v & 0x00FF0000u) >> 8)
         | ((v & 0xFF000000u) >> 24);
}

/* -------------------------------------------------------------------------- */
/* Barriers                                                                    */
/* -------------------------------------------------------------------------- */
static inline void rci_compiler_barrier(void)
{
#if defined(__GNUC__)
    __asm__ volatile ("" ::: "memory");
#else
    (void)0; /* fallback no-op */
#endif
}

static void rci_mb(void)
{
#if defined(__arm__) || defined(__aarch64__)
    __asm__ volatile ("dmb sy" ::: "memory");
#elif defined(__riscv)
    __asm__ volatile ("fence rw, rw" ::: "memory");
#else
    __sync_synchronize();
#endif
}

static void rci_rmb(void)
{
    rci_mb();
}

static void rci_wmb(void)
{
    rci_mb();
}

/* -------------------------------------------------------------------------- */
/* MMIO accessors (big-endian register view)                                   */
/* -------------------------------------------------------------------------- */
static inline uintptr_t rci_addr(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off)
{
    return (ctx->base + (uintptr_t)off);
}

static uint8_t rci_read8(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off)
{
    const volatile uint8_t *p = (const volatile uint8_t *)rci_addr(ctx, off);
    rci_compiler_barrier();
    uint8_t v = *p;
    rci_compiler_barrier();
    return v;
}

static void rci_write8(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off, uint8_t val)
{
    volatile uint8_t *p = (volatile uint8_t *)rci_addr(ctx, off);
    rci_compiler_barrier();
    *p = val;
    rci_compiler_barrier();
}

static uint16_t rci_read16(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off)
{
    const volatile uint16_t *p = (const volatile uint16_t *)rci_addr(ctx, off);
    rci_compiler_barrier();
    uint16_t v = *p;
    rci_compiler_barrier();
#if RCI_CPU_LITTLE_ENDIAN
    v = rci_bswap16(v);
#endif
    return v;
}

static void rci_write16(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off, uint16_t val)
{
    volatile uint16_t *p = (volatile uint16_t *)rci_addr(ctx, off);
#if RCI_CPU_LITTLE_ENDIAN
    uint16_t be = rci_bswap16(val);
#else
    uint16_t be = val;
#endif
    rci_compiler_barrier();
    *p = be;
    rci_compiler_barrier();
}

static uint32_t rci_read32(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off)
{
    const volatile uint32_t *p = (const volatile uint32_t *)rci_addr(ctx, off);
    rci_compiler_barrier();
    uint32_t v = *p;
    rci_compiler_barrier();
#if RCI_CPU_LITTLE_ENDIAN
    v = rci_bswap32(v);
#endif
    return v;
}

static void rci_write32(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off, uint32_t val)
{
    volatile uint32_t *p = (volatile uint32_t *)rci_addr(ctx, off);
#if RCI_CPU_LITTLE_ENDIAN
    uint32_t be = rci_bswap32(val);
#else
    uint32_t be = val;
#endif
    rci_compiler_barrier();
    *p = be;
    rci_compiler_barrier();
}

/* -------------------------------------------------------------------------- */
/* Public API                                                                  */
/* -------------------------------------------------------------------------- */
static const TMS320C6452_DSP_core_ops rci_ops = {
    .read8  = rci_read8,
    .write8 = rci_write8,
    .read16 = rci_read16,
    .write16= rci_write16,
    .read32 = rci_read32,
    .write32= rci_write32,
    .rmb    = rci_rmb,
    .wmb    = rci_wmb,
    .mb     = rci_mb
};

void TMS320C6452_DSP_core_init(TMS320C6452_DSP_core_ctx *ctx, uintptr_t base)
{
    if (ctx != NULL) {
        ctx->base = base;
    }
}

const TMS320C6452_DSP_core_ops *TMS320C6452_DSP_core_get_ops(void)
{
    return &rci_ops;
}
