/*
 * TMS320C6452 DSP Core MMIO Access - Reusable Core Layer
 * Generated by RCI-ag-DrvGen Agent
 */
#ifndef TMS320C6452_DSP_CORE_H
#define TMS320C6452_DSP_CORE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* Base address for the device register window */
#define TMS320C6452_DSP_BASE              (0xA1008000u)

/* Exemplar offsets for a GPIO-like register block (placeholder; verify against TRM) */
#define TMS320C6452_DSP_GPIO_DATAIN_OFFSET       (0x0000u)
#define TMS320C6452_DSP_GPIO_DATAOUT_OFFSET      (0x0004u)
#define TMS320C6452_DSP_GPIO_DIR_OFFSET          (0x0008u)
#define TMS320C6452_DSP_GPIO_SET_OFFSET          (0x000Cu)
#define TMS320C6452_DSP_GPIO_CLR_OFFSET          (0x0010u)
#define TMS320C6452_DSP_GPIO_INT_EN_OFFSET       (0x0014u)
#define TMS320C6452_DSP_GPIO_INT_TYPE_OFFSET     (0x0018u)
#define TMS320C6452_DSP_GPIO_INT_POL_OFFSET      (0x001Cu)
#define TMS320C6452_DSP_GPIO_INT_STATUS_OFFSET   (0x0020u)

/* Forward declaration of core context */
typedef struct TMS320C6452_DSP_core_ctx {
    uintptr_t base; /* base MMIO address */
} TMS320C6452_DSP_core_ctx;

/* Core ops for MMIO and barriers (big-endian register view) */
typedef struct TMS320C6452_DSP_core_ops {
    /* 8-bit */
    uint8_t  (*read8)(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off);
    void     (*write8)(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off, uint8_t val);
    /* 16-bit (big-endian on the bus) */
    uint16_t (*read16)(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off);
    void     (*write16)(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off, uint16_t val);
    /* 32-bit (big-endian on the bus) */
    uint32_t (*read32)(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off);
    void     (*write32)(const TMS320C6452_DSP_core_ctx *ctx, uint32_t off, uint32_t val);

    /* Memory barriers */
    void (*rmb)(void); /* Read memory barrier */
    void (*wmb)(void); /* Write memory barrier */
    void (*mb)(void);  /* Full memory barrier */
} TMS320C6452_DSP_core_ops;

/* Initialize a core context with a base address (use TMS320C6452_DSP_BASE for default) */
void TMS320C6452_DSP_core_init(TMS320C6452_DSP_core_ctx *ctx, uintptr_t base);

/* Retrieve the singleton ops table */
const TMS320C6452_DSP_core_ops *TMS320C6452_DSP_core_get_ops(void);

#ifdef __cplusplus
}
#endif

#endif /* TMS320C6452_DSP_CORE_H */
